FROM ubuntu:12.04
FROM golang:1.6

ADD . /go/src/gitlab.rd.unicloud.com/Storage-oss-service/uos-sdk-go.git

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/gitlab.rd.unicloud.com/Storage-oss-service/uos-sdk-go.git
CMD ["make", "unit-old-go-race-cover"]
