FROM ubuntu:12.04
FROM golang:1.11

ADD . /go/src/github.com/unicloud-uos/uos-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/github.com/unicloud-uos/uos-sdk-go
CMD ["make", "unit"]
